p8105_hw2_zn2220
================
Ziang Niu
2025-09-24

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(lubridate)
library(readxl)
library(haven)
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
library(knitr)
```

# Problem 1

## 1.1

### First, clean the data in pols-month.csv. Use separate() to break up the variable mon into integer variables year, month, and day; replace month number with month name; create a president variable taking values gop and dem, and remove prez_dem and prez_gop; and remove the day variable.

``` r
pols_df <- read_csv("data/pols-month.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  separate(
    mon, into = c("year", "month", "day"), sep = "-"
  ) %>% 
  mutate(
    year = as.integer(year),
    month = factor(
      month.name[as.integer(month)],
      levels = month.name,
      ordered = TRUE
    )
  ) %>% 
  mutate(
    president = case_when(
      prez_dem == 1 ~ "dem",
      prez_gop == 1 ~ "gop",
      TRUE ~ NA_character_
    )
  ) %>% 
  select(-prez_dem, -prez_gop, -day) %>% 
  select(year, month, everything())
```

``` r
pols_df
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <ord>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

## 1.2

### Second, clean the data in snp.csv using a similar process to the above. For consistency across datasets, arrange according to year and month, and organize so that year and month are the leading columns.

``` r
snp_df = 
  read_csv("data/snp.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  separate(
    date, into = c("month", "day", "year"), sep = "/"
  ) %>% 
  mutate(
    year = if_else(
      as.integer(year) <= 15,
      as.integer(year) + 2000,
      as.integer(year) + 1900
    ),
    month = factor(
      month.name[as.integer(month)], 
      levels = month.name, ordered = TRUE
    )
  ) %>% 
  select(-day) %>% 
  arrange(year, month) %>% 
  select(year, month, everything())
```

``` r
snp_df
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <dbl> <ord>     <dbl>
    ##  1  1950 January    17.0
    ##  2  1950 February   17.2
    ##  3  1950 March      17.3
    ##  4  1950 April      18.0
    ##  5  1950 May        18.8
    ##  6  1950 June       17.7
    ##  7  1950 July       17.8
    ##  8  1950 August     18.4
    ##  9  1950 September  19.5
    ## 10  1950 October    19.5
    ## # ℹ 777 more rows

## 1.3

### Third, tidy the unemployment data so that it can be merged with the previous datasets. This process will involve switching from “wide” to “long” format; ensuring that key variables have the same name; and ensuring that key variables take the same values.

``` r
une_df = 
  read_csv("data/unemployment.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment",
  ) %>% 
  mutate(
    month = factor(
      month,
      levels = tolower(month.abb),
      labels = month.name,
      ordered = TRUE 
    )
  ) %>% 
  select(year, month, everything())
```

``` r
une_df
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment
    ##    <dbl> <ord>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ℹ 806 more rows

## 1.4

### Join the datasets by merging snp into pols, and merging unemployment into the result.

``` r
overall_df <- pols_df %>% 
  full_join(snp_df, by = c("year", "month")) %>% 
  full_join(une_df, by = c("year", "month")) %>% 
  janitor::clean_names()
```

## 1.5

### Write a short paragraph about these datasets. Explain briefly what each dataset contained, and describe the resulting dataset (e.g. give the dimension, range of years, and names of key variables).

The pols_df contains:

``` r
summary(pols_df)
```

    ##       year           month        gov_gop         sen_gop        rep_gop     
    ##  Min.   :1947   January : 69   Min.   :12.00   Min.   :32.0   Min.   :141.0  
    ##  1st Qu.:1964   February: 69   1st Qu.:18.00   1st Qu.:42.0   1st Qu.:176.0  
    ##  Median :1981   March   : 69   Median :22.00   Median :46.0   Median :195.0  
    ##  Mean   :1981   April   : 69   Mean   :22.48   Mean   :46.1   Mean   :194.9  
    ##  3rd Qu.:1998   May     : 69   3rd Qu.:28.00   3rd Qu.:51.0   3rd Qu.:222.0  
    ##  Max.   :2015   June    : 69   Max.   :34.00   Max.   :56.0   Max.   :253.0  
    ##                 (Other) :408                                                 
    ##     gov_dem        sen_dem         rep_dem     president        
    ##  Min.   :17.0   Min.   :44.00   Min.   :188   Length:822        
    ##  1st Qu.:22.0   1st Qu.:48.00   1st Qu.:211   Class :character  
    ##  Median :28.0   Median :53.00   Median :250   Mode  :character  
    ##  Mean   :27.2   Mean   :54.41   Mean   :245                     
    ##  3rd Qu.:32.0   3rd Qu.:58.00   3rd Qu.:268                     
    ##  Max.   :41.0   Max.   :71.00   Max.   :301                     
    ## 

The snp_df contains:

``` r
summary(snp_df)
```

    ##       year           month         close        
    ##  Min.   :1950   January : 66   Min.   :  17.05  
    ##  1st Qu.:1966   February: 66   1st Qu.:  83.73  
    ##  Median :1982   March   : 66   Median : 138.53  
    ##  Mean   :1982   April   : 66   Mean   : 474.89  
    ##  3rd Qu.:1999   May     : 66   3rd Qu.: 941.80  
    ##  Max.   :2015   June    : 66   Max.   :2107.39  
    ##                 (Other) :391

The une_df contains:

``` r
summary(une_df)
```

    ##       year           month      unemployment  
    ##  Min.   :1948   January : 68   Min.   : 2.50  
    ##  1st Qu.:1965   February: 68   1st Qu.: 4.70  
    ##  Median :1982   March   : 68   Median : 5.60  
    ##  Mean   :1982   April   : 68   Mean   : 5.83  
    ##  3rd Qu.:1998   May     : 68   3rd Qu.: 6.90  
    ##  Max.   :2015   June    : 68   Max.   :10.80  
    ##                 (Other) :408   NA's   :6

The combined dataset `overall_df` can be summarized with the following R
functions:

- The dimension is 828 x 11.  
- The range of year is from 1947 to 2015.  
- The key variables are: year, month, gov_gop, sen_gop, rep_gop,
  gov_dem, sen_dem, rep_dem, president, close, unemployment.  
- A descriptive summary of each variable is:

``` r
summary(overall_df)
```

    ##       year           month        gov_gop         sen_gop        rep_gop     
    ##  Min.   :1947   January : 69   Min.   :12.00   Min.   :32.0   Min.   :141.0  
    ##  1st Qu.:1964   February: 69   1st Qu.:18.00   1st Qu.:42.0   1st Qu.:176.0  
    ##  Median :1981   March   : 69   Median :22.00   Median :46.0   Median :195.0  
    ##  Mean   :1981   April   : 69   Mean   :22.48   Mean   :46.1   Mean   :194.9  
    ##  3rd Qu.:1998   May     : 69   3rd Qu.:28.00   3rd Qu.:51.0   3rd Qu.:222.0  
    ##  Max.   :2015   June    : 69   Max.   :34.00   Max.   :56.0   Max.   :253.0  
    ##                 (Other) :414   NA's   :6       NA's   :6      NA's   :6      
    ##     gov_dem        sen_dem         rep_dem     president        
    ##  Min.   :17.0   Min.   :44.00   Min.   :188   Length:828        
    ##  1st Qu.:22.0   1st Qu.:48.00   1st Qu.:211   Class :character  
    ##  Median :28.0   Median :53.00   Median :250   Mode  :character  
    ##  Mean   :27.2   Mean   :54.41   Mean   :245                     
    ##  3rd Qu.:32.0   3rd Qu.:58.00   3rd Qu.:268                     
    ##  Max.   :41.0   Max.   :71.00   Max.   :301                     
    ##  NA's   :6      NA's   :6       NA's   :6                       
    ##      close          unemployment  
    ##  Min.   :  17.05   Min.   : 2.50  
    ##  1st Qu.:  83.73   1st Qu.: 4.70  
    ##  Median : 138.53   Median : 5.60  
    ##  Mean   : 474.89   Mean   : 5.83  
    ##  3rd Qu.: 941.80   3rd Qu.: 6.90  
    ##  Max.   :2107.39   Max.   :10.80  
    ##  NA's   :41        NA's   :18

### Note

Create the data key.

``` r
overall_df <- overall_df %>%
  mutate(date = lubridate::make_date(year, as.integer(month)))
```

# Problem 2

## 2.1

### Read and clean the Mr. Trash Wheel sheet:specify the sheet in the Excel file and to omit non-data entries (rows with notes / figures; columns containing notes) using arguments in read_excel. Use reasonable variable names. Omit rows that do not include dumpster-specific data. Round the number of sports balls to the nearest integer and converts the result to an integer variable (using as.integer)

``` r
mtw_df <- read_excel(
  "data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  skip = 1
) %>%
  select(-...15, -...16) %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    year = as.integer(year),
    wheel = "Mr. Trash Wheel"
  )
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

## 2.2

### Use a similar process to import, clean, and organize the data for Professor Trash Wheel and Gwynnda, and combine this with the Mr. Trash Wheel dataset to produce a single tidy dataset. To keep track of which Trash Wheel is which, you may need to add an additional variable to both datasets before combining.

``` r
ptw_df <- read_excel(
  "data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  skip = 1
) %>%
  select(-starts_with("...")) %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(
    year = as.integer(year),
    wheel = "Professor Trash Wheel"
  )

gtw_df <- read_excel(
  "data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynns Falls Trash Wheel",
  skip = 1
) %>%
  select(-starts_with("...")) %>%
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(
    year = as.integer(year),
    wheel = "Gwynnda Trash Wheel"
  )
```

Combine.

``` r
wheelall_df <- bind_rows(mtw_df, ptw_df, gtw_df) %>%
  filter(!is.na(date)) %>%
  arrange(date, wheel)
```

## 2.3

### Write a paragraph about these data; you are encouraged to use inline R. Be sure to note the number of observations in the resulting dataset, and give examples of key variables. For available data, what was the total weight of trash collected by Professor Trash Wheel? What was the total number of cigarette butts collected by Gwynnda in June of 2022?

The combined dataset of Trash Wheel collections contains 1188
observations, with key variables including:

``` r
names(wheelall_df)
```

    ##  [1] "dumpster"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "glass_bottles"      "plastic_bags"       "wrappers"          
    ## [13] "sports_balls"       "homes_powered"      "wheel"

Professor Trash Wheel collected a total of 282.26 tons of trash. In
addition, Gwynnda Trash Wheel collected 1.812^{4} cigarette butts in
June of 2022.

# Problem 3

## 3.1

### Create a single, well-organized dataset with all the information contained in these data files. To that end: import, clean, tidy, and otherwise wrangle each of these datasets; check for completeness and correctness across datasets (e.g. by viewing individual datasets and monitoring warning messages); merge to create a single, final dataset; and organize this so that variables and observations are in meaningful orders.

Clean and see, Transformation and Combination.

``` r
final_data <- read_csv("data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") %>%
  pivot_longer(
    cols = starts_with("20"),
    names_to = "period",
    values_to = "value"
  ) %>%
  transmute(
    postal_code = as.character(RegionName),
    period = ymd(period),
    value
  ) %>%
  left_join(
    read_csv("data/Zip Codes.csv") %>%
      clean_names() %>%
      mutate(postal_code = as.character(zip_code)),
    by = "postal_code"
  ) %>%
  select(
    postal_code,
    borough = county,
    area = neighborhood,
    period,
    value
  ) %>%
  arrange(postal_code, period)
```

    ## Warning in left_join(., read_csv("data/Zip Codes.csv") %>% clean_names() %>% : Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 4757 of `x` matches multiple rows in `y`.
    ## ℹ Row 256 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

## 3.2

### Briefly describe the resulting tidy dataset. How many total observations exist? How many unique ZIP codes are included, and how many unique neighborhoods?

The resulting tidy dataset combines rental index data with geographic
information for New York City. Each observation represents the rental
index for a single postal code in a given month. The dataset includes a
total of 17516 observations. It covers 149 unique postal codes and 43
unique areas (neighborhoods). Key variables include postal_code,
borough, area, period, and the rental index value.

``` r
glimpse(final_data)
```

    ## Rows: 17,516
    ## Columns: 5
    ## $ postal_code <chr> "10001", "10001", "10001", "10001", "10001", "10001", "100…
    ## $ borough     <chr> "New York", "New York", "New York", "New York", "New York"…
    ## $ area        <chr> "Chelsea and Clinton", "Chelsea and Clinton", "Chelsea and…
    ## $ period      <date> 2015-01-31, 2015-02-28, 2015-03-31, 2015-04-30, 2015-05-3…
    ## $ value       <dbl> 3855.089, 3892.376, 3898.212, 3969.644, 4033.221, 4070.808…

## 3.3

### Which ZIP codes appear in the ZIP code dataset but not in the Zillow Rental Price dataset? Using a few illustrative examples discuss why these ZIP codes might be excluded from the Zillow dataset.

``` r
zips_missing <- read_csv("data/Zip Codes.csv") %>%
  clean_names() %>%
  mutate(postal_code = as.character(zip_code)) %>%
  anti_join(final_data, by = "postal_code")
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zips_missing
```

    ## # A tibble: 171 × 8
    ##    county state_fips county_code county_fips zip_code file_date neighborhood    
    ##    <chr>       <dbl> <chr>             <dbl>    <dbl> <chr>     <chr>           
    ##  1 Bronx          36 005               36005    10464 7/25/07   Southeast Bronx 
    ##  2 Bronx          36 005               36005    10474 7/25/07   Hunts Point and…
    ##  3 Bronx          36 005               36005    10475 7/25/07   Northeast Bronx 
    ##  4 Bronx          36 005               36005    10499 7/25/07   <NA>            
    ##  5 Bronx          36 005               36005    10550 7/25/07   <NA>            
    ##  6 Bronx          36 005               36005    10704 7/25/07   <NA>            
    ##  7 Bronx          36 005               36005    10705 7/25/07   <NA>            
    ##  8 Bronx          36 005               36005    10803 7/25/07   <NA>            
    ##  9 Kings          36 047               36047    11202 7/25/07   <NA>            
    ## 10 Kings          36 047               36047    11224 7/25/07   Southern Brookl…
    ## # ℹ 161 more rows
    ## # ℹ 1 more variable: postal_code <chr>

Some ZIP codes appear in the reference file but not in Zillow’s rental
dataset because they do not represent active residential markets. In
many cases these areas are primarily commercial or industrial, or they
contain very few rental properties, making it difficult for Zillow to
calculate a reliable rent index. In other instances, the ZIP codes may
be newly created or used mainly for postal delivery rather than for
households. Finally, the scope of the Zillow dataset is limited to
neighborhoods where sufficient rental activity is observed, so ZIP codes
outside the core residential areas of New York City are naturally
excluded.

## 3.4

### Rental prices fluctuated dramatically during the COVID-19 pandemic. For all available ZIP codes, compare rental prices in January 2021 to prices in January 2020. Make a table that shows the 10 ZIP codes (along with the borough and neighborhood) with largest drop in price from January 2020 to 2021. Comment.

``` r
top10_drop <- final_data %>%
  filter(period %in% c(ymd("2020-01-31"), ymd("2021-01-31"))) %>%
  pivot_wider(
    names_from = period,
    values_from = value
  ) %>%
  mutate(rent_drop = `2020-01-31` - `2021-01-31`) %>%
  drop_na(rent_drop) %>%
  arrange(desc(rent_drop)) %>%
  head(10) %>%
  select(postal_code, borough, area, rent_drop)

kable(
  top10_drop,
  col.names = c("ZIP Code", "Borough", "Neighborhood", "Rent Drop ($)"),
  caption = "Top 10 ZIP Codes by Largest Rent Decrease (Jan 2020 to Jan 2021)",
  digits = 2
)
```

| ZIP Code | Borough  | Neighborhood                  | Rent Drop (\$) |
|:---------|:---------|:------------------------------|---------------:|
| 10007    | New York | Lower Manhattan               |         912.60 |
| 10069    | New York | NA                            |         748.12 |
| 10009    | New York | Lower East Side               |         714.25 |
| 10016    | New York | Gramercy Park and Murray Hill |         711.70 |
| 10001    | New York | Chelsea and Clinton           |         710.45 |
| 10002    | New York | Lower East Side               |         710.30 |
| 10004    | New York | Lower Manhattan               |         705.96 |
| 10038    | New York | Lower Manhattan               |         697.59 |
| 10012    | New York | Greenwich Village and Soho    |         686.22 |
| 10010    | New York | Gramercy Park and Murray Hill |         684.93 |

Top 10 ZIP Codes by Largest Rent Decrease (Jan 2020 to Jan 2021)

The values range from about -912.6 to -684.9, and Lower Manhattan
appears most often with the lowest values.
